Refactor & add reply/delete
GoldsteinE/tg-vimhelpbot pull request #1
Opened 2020-12-03 22:40 UTC by kraftwerk28

Add reply/delete

2020-12-07 18:34 UTC, GoldsteinE requested changes
Cool with minor problems

2020-12-07 18:34 UTC, GoldsteinE commented on src/main.rs
> +                    message.delete_message().send().await.ok();
With this change bot won't delete message if it's _not_ a reply — I think, it's incorrect behaviour.

2020-12-07 18:34 UTC, GoldsteinE commented on src/main.rs
> +                if let Ok(_) = sent_ans.send().await {
```suggestion
                if sent_ans.send().await.is_ok() {
```

2020-12-07 18:34 UTC, GoldsteinE commented on src/tagsearch.rs
> +pub struct TagSearch {
Type names should be nouns, not verbs.

2020-12-07 18:34 UTC, GoldsteinE commented on src/main.rs
>  async fn run() -> i32 {
Seems like `run()` can't return non-zero anymore, why keep `-> i32`?

2021-01-02 19:34 UTC, GoldsteinE commented on src/main.rs
> +    Dispatcher::new(bot)
А почему не repl?

2021-01-02 19:36 UTC, GoldsteinE commented on src/tagsearch.rs
> +            .expect("Failed to parse Vim db");
I don't really like panicking in this case: should be an error, IMO

2021-01-02 19:40 UTC, kraftwerk28 commented on src/main.rs
> +    Dispatcher::new(bot)
If more handlers will be added in future, it will be turned to `Dispatcher` anyway, so why not. `repl` is intended for quick prototyping

2021-01-02 20:02 UTC, kraftwerk28 commented on src/main.rs
> -    dotenv::dotenv().ok();
Why deleted this line?

2021-01-03 23:54 UTC, GoldsteinE commented on src/main.rs
> +    Dispatcher::new(bot)
I'm for the most simple working solution. There is no need to manually write what's already written in `teloxide`.

2021-01-03 23:58 UTC, GoldsteinE commented on src/main.rs
> -    dotenv::dotenv().ok();
By accident, already brought it back.

2021-01-04 00:17 UTC, GoldsteinE approved these changes

2021-01-04 00:17 UTC, merged